#!/bin/sh

source /opt/wz_mini/wz_mini.conf

echo "Replace stock busybox"
mount --bind /opt/wz_mini/bin/busybox /bin/busybox

echo "Replace stock fstab"
mount --bind /opt/wz_mini/etc/fstab /etc/fstab

echo "Replace stock inittab"
mount --bind /opt/wz_mini/etc/inittab /etc/inittab

echo "Bind /etc/profile for local/ssh shells"
mount --bind /opt/wz_mini/etc/profile /etc/profile

if [ -d /lib/modules ]; then
        echo "Mount kernel modules in /lib"
        mount --bind /opt/wz_mini/lib/modules /lib/modules
fi

echo "Replace hostname"
echo $CUSTOM_HOSTNAME > /opt/wz_mini/etc/hostname
mount --bind /opt/wz_mini/etc/hostname /etc/hostname
