#!/bin/sh

source /opt/wz_mini/wz_mini.conf

echo "Mount wz_mini tmpfs"
mount -t tmpfs /opt/wz_mini/tmp

echo "Create workspace directory"
mkdir /opt/wz_mini/tmp/.storage

echo "Mounting global tmpfs"
mount -t tmpfs /tmp
