#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Short-Description: Mount tmpfs
# Description:       Mount tmpfs for system and wz_mini
### END INIT INFO

./opt/wz_mini/wz_mini.conf

case "$1" in
	start)

		echo "#####$(basename "$0")#####"

		echo "Mount wz_mini tmpfs"
		mount -t tmpfs /opt/wz_mini/tmp

		echo "Create workspace directory"
		mkdir /opt/wz_mini/tmp/.storage

		echo "Mounting global tmpfs"
		mount -t tmpfs /tmp

		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

