#!/bin/sh

if [ -d /opt/wz_mini/usr/share/terminfo ]; then
        echo "Terminfo already present"
else
        echo "Terminfo not present, extract"
        tar xf /opt/wz_mini/usr/share/terminfo.tar -C /opt/wz_mini/usr/share/
fi
