#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Short-Description: Patches the iCamera binary if in self-hosted mode
# Description:       Disabled to avoid patching stock Wyze iCamera behavior.
### END INIT INFO

exit 0
