#wz_mini configuration (USB Ethernet focused)

#####NETWORKING#####
CUSTOM_HOSTNAME="WCV3"
ENABLE_USB_ETH="true"
ENABLE_USB_ETH_MODULE_AUTODETECT="true"
ENABLE_USB_ETH_MODULE_MANUAL=""
USB_ETH_MAC_ADDR=""

#####BOOT/DRIVER SAFETY#####
ENABLE_RTL8189FS_DRIVER="false"
ENABLE_ATBM603X_DRIVER="false"
ENABLE_SWAP="false"
DISABLE_FW_UPGRADE="true"
AUDIO_PROMPT_VOLUME="50"

#####SCRIPTING#####
CUSTOM_SCRIPT_PATH=""
