#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Short-Description: WLAN HW Init check
# Description:       Make sure the WLAN hardware is functional and initialized before proceeding.
### END INIT INFO

. /opt/wz_mini/etc/rc.common

case "$1" in
	start)
		echo "#####$(basename "$0")#####"

		#Wait for wlan hardware to be intitialized in app_init.sh, this must be blocking
		echo "Waiting for wlan hw init"
		wait_for_wlan $(basename "$0")
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

