#!/bin/sh

if [ -e /tmp/dbgflag ]; then
	echo "debug enabled, rc.d disabled."
	exit 0
fi

for i in /opt/wz_mini/etc/rc.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	     *.sh)
		     # Source shell script for speed.
		     (
		     trap - INT QUIT TSTP
		     set start
		     . $i
	     )
	     ;;
     *)
	     # No sh extension, so fork subprocess.
	     $i start
	     ;;
esac
done
