#!/bin/sh

source /opt/wz_mini/etc/rc.common
source /opt/wz_mini/wz_mini.conf

if [[ "$ENABLE_USB_DIRECT" == "true" ]]; then

        HOST_MACADDR=$(echo "$CUSTOM_HOSTNAME"|md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
	        if [ -f /opt/wz_mini/tmp/.T20 ]; then
                echo connect > /sys/devices/platform/jz-dwc2/dwc2/udc/dwc2/soft_connect
                sleep 1
               	devmem 0x10000040 32 0x0b800096
       	        sleep 1
                devmem 0x13500000 32 0x001100cc
        else
                #Set dwc2 ID_PIN driver memory
                devmem 0x13500000 32 0x001100cc
                devmem 0x10000040 32 0x0b000096
                #wipe the bits to set the ID_PIN, only for the V3.
                devmem 0x10000040 32 0x0b000FFF
        fi

        insmod $KMOD_PATH/kernel/drivers/usb/gadget/libcomposite.ko

        if [ -f /opt/wz_mini/tmp/.T31 ]; then
	        insmod /opt/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__/kernel/drivers/usb/gadget/u_ether.ko
        	insmod /opt/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__/kernel/drivers/usb/gadget/usb_f_ncm.ko
        fi

	insmod $KMOD_PATH/kernel/drivers/usb/gadget/g_ncm.ko iManufacturer=wz_mini_ncm host_addr="$HOST_MACADDR" dev_addr="$USB_DIRECT_MAC_ADDR"

	echo "USB Direct enabled"

else
        echo "USB Direct disabled"

fi
