#!/bin/sh

source /opt/wz_mini/etc/rc.common
source /opt/wz_mini/wz_mini.conf

alternate_iface() {

	if [[ "$ENABLE_USB_ETH" == "true" ]] || [[ "$ENABLE_USB_DIRECT" == "true" ]] || [[ "$ENABLE_USB_RNDIS" == "true" ]]; then

	wait_for_wlan_wpa

	##Fool iCamera by renaming the hardline interface to wlan0
        echo "Renaming interfaces"
        ifconfig $ALT_IFACE down

        ifconfig wlan0 down
        /opt/wz_mini/bin/busybox ip link set wlan0 name wlanold
        /opt/wz_mini/bin/busybox ip addr flush dev wlanold
        /opt/wz_mini/bin/busybox ip link set $ALT_IFACE name wlan0

        if [ -f /opt/wz_mini/tmp/.T20 ]; then
	        mount -o bind /opt/wz_mini/bin/wpa_cli.sh /system/bin/wpa_cli
        else
	        mount -o bind /opt/wz_mini/bin/wpa_cli.sh /bin/wpa_cli
	fi

	else
		echo "No alternate iface enabled"
	fi

}

if ! [[ "$BONDING_ENABLED" == "true" ]]; then
    alternate_iface &
fi
