#!/bin/sh

source /opt/wz_mini/etc/rc.common

set -x

core() {

	#Kill dumpload so it won't waste cpu or ram gathering cores and uploading them when something crashes
	wait_for_wlan_wpa

	echo "killing dumpload"
	/opt/wz_mini/bin/busybox pkill -f dumpload
}

sysctl -w kernel.core_pattern='|/bin/false'

core &
