#!/bin/sh

source /opt/wz_mini/etc/rc.common
source /opt/wz_mini/wz_mini.conf


mp4write() {

wait_for_icamera

if [[ "$ENABLE_MP4_WRITE" == "true" ]]; then
        if [ -f /opt/wz_mini/tmp/.T20 ]; then
                echo "mp4_write is not supported on T20"
        else
                /opt/wz_mini/bin/cmd mp4write on
                echo "mp4_write enabled"
        fi
else
        echo "mp4_write disabled"
fi
}

mp4write &
