#!/bin/sh

source /opt/wz_mini/wz_mini.conf

if [[ "$ENABLE_LOCAL_DNS" == "true" ]]; then
	dnsmasq -C /opt/wz_mini/etc/dnsmasq.conf
	rm -f /tmp/resolv.conf
	cp /opt/wz_mini/etc/resolv.conf /tmp/resolv.conf
fi

