#!/bin/sh
## Initramfs init

set -x

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir /sdcard
mkdir /stock_rootfs
mkdir /newroot
sleep 3 # It takes maximum 3 seconds to detect SD card on /dev

mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000
mount -t squashfs /dev/mtdblock2 /stock_rootfs
	
move_mountpoint() { # Move virtual file systems to new root
	echo "Moving /dev,/sys,/proc,/sdcard,/stock_rootfs to /new_root"
	mount --move /dev /newroot/dev
	mount --move /sys /newroot/sys
	mount --move /proc /newroot/proc
	mount --move /sdcard /newroot/opt
}

run_overlay() { # Boot with overlayfs
	mkdir /wz_mini-upper
	[ ! -d /sdcard/wz_mini-overlay ] && { echo "/sdcard/wz_mini-overlay dir isn't present, making one"; mkdir /sdcard/wz_mini-overlay; }
	
	mount --bind /sdcard/wz_mini-overlay /wz_mini-upper
	mount -t overlayfs overlayfs -olowerdir=/stock_rootfs,upperdir=/wz_mini-upper /newroot

	[ ! -d /newroot/stock_rootfs ] && mkdir /newroot/stock_rootfs
	[ ! -d /newroot/wz_mini-upper ] && mkdir /newroot/wz_mini-upper

	move_mountpoint
	mount --move /stock_rootfs /newroot/stock_rootfs
	mount --move /wz_mini-upper /newroot/wz_mini-upper
	
	echo "Switching to /newroot with Overlayfs"
	exec busybox switch_root /newroot /opt/wz_mini/etc/init.d/wz_init.sh
}

run_stock() { # Boot stock
	mount --move /stock_rootfs /newroot
	move_mountpoint
	exec busybox switch_root /newroot /linuxrc
}


WZMINI_CONF=/sdcard/wz_mini/wz_mini.conf
## Stock boot or debug mode
if [ ! -f $WZMINI_CONF ]; then
	echo "Unable to find /sdcard/wz_mini/etc/init.d/wz_mini.conf, booting to stock"
	run_stock
else
	source $WZMINI_CONF
	if [[ "$DEBUG_INITRAMFS_ENABLED" == "true" ]]; then  # Check if DEBUG MODE enabled
		echo "Starting initramfs debug mode"
		exec /bin/sh
	fi
fi

## 
if [[ "$USE_OVERLAYFS" == "true" ]]; then
	echo "USE_OVERLAYFS option: true"
	run_overlay
else
	echo "USE_OVERLAYFS option: false"
	run_stock
fi
